
name: crm

services:
  crm-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CRM_ENVIRONMENT=dev
      - DB_URL=postgresql+asyncpg://postgres:example@crm-db:5432/crm
      - JWT_SECRET_KEY=1a9a444f13a975cb125b74e24c3a9a741d9a45294c01c0462b6167c232f47915
      - JWT_EXPIRATION_MINUTES=30
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - crm-db
    pull_policy: never
    volumes:
      - ./mount:/mount

  crm-db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: crm
    ports:
      - "5432:5432"
