"""create_organisation_table

Revision ID: 6e8951d71bd2
Revises: f8c708501039
Create Date: 2025-07-30 18:29:57.459838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8951d71bd2'
down_revision: Union[str, Sequence[str], None] = 'f8c708501039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('user_type', sa.String(), nullable=False))
    op.add_column('users', sa.Column('organisation_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'organisations', ['organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organisation_id')
    op.drop_column('users', 'user_type')
    op.drop_table('organisations')
    # ### end Alembic commands ###
